My Project: Windlog.h File Reference
Windlog.h File Reference
#include <iostream>
#include "Date.h"
#include "Time.h"
#include "Vector.h"
#include "Weather.h"
Classes
class WindLog
WindLog Class is created to store the Date Class, Time Class and Weather Class.
Functions
ostream & operator<< (ostream &os, const WindLog &windlog)
istream & operator>> (istream &input, WindLog &windlog)
an overload output operator. Use to output the object or result
Function Documentation
operator<<()
ostream & operator<< (ostream & os, const WindLog & windlog)
Definition at line 48 of file Windlog.cpp.
{
    os
    << windlog.GetDate() << "\n"
    <<"Time: " << windlog.GetTime() << "\n"
    << windlog.GetWeather()<< endl;
    return os;
}
operator>>()
istream & operator>> (istream & input, WindLog & windlog)
an overload output operator. Use to output the object or result
Parameters
ostream is reference to OS. That is use for the output stream using the #include <iostream> header
windlog is just a object variable name that we created for windlog.CPP ostream operator.
Definition at line 58 of file Windlog.cpp.
{
    Date date;
    Time time;
    Weather weather;
    input >> date;
    windlog.SetDate(date);
    input >> time;
    windlog.SetTime(time);
    input >> weather;
    windlog.SetWeather(weather);
    return input;
}
References WindLog::SetDate(), WindLog::SetTime(), and WindLog::SetWeather().